In [7]:
# required packages
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.model_selection import cross_val_score
import scipy as sp
import nltk
#from combined import combined
from sklearn.cross_validation import KFold
from sklearn.metrics import confusion_matrix
from textstat.textstat import textstat
from sklearn.model_selection import train_test_split

In [14]:
#START HERE - THIS CODE IS FOR TRYING THE CLASSIFIER
#read data by set
set1 = pd.read_csv("short_set_expr1.csv")
set2 = pd.read_csv("short_set_expr2.csv")
set3 = pd.read_csv("short_set_expr3.csv")
set4 = pd.read_csv("short_set_expr3.csv")
set5 = pd.read_csv("short_set_expr5.csv")
set6 = pd.read_csv("short_set_expr6.csv")
set7 = pd.read_csv("short_set_expr7.csv")
set8 = pd.read_csv("short_set_expr8.csv")
set9 = pd.read_csv("short_set_expr9.csv")
set10 = pd.read_csv("short_set_expr10.csv")

In [16]:
# put all sets into a list for easy processing
all_data = [set1,set2,set3, set4,set5,set6 ,set7, set8, set9,set10]

In [18]:
# for each set, get an array of features and an array of scores, and input these to classifier
set_num = 0
set_array = [1,2,3,4,5,6,7,8,9,10] #number of each set in the all_data list
for s in all_data:
    print("Splitting data for set ", set_array[set_num])
    #split into array of scores and array of other features
    scores = []
    features = []
    i = 0
    for row in s.itertuples(index=True, name='Pandas'):
        scores.append(getattr(row, "score"))
        features.append([])
        features[i].append(getattr(row, "org_score"))
        features[i].append(getattr(row, "pos_adjadv"))
        features[i].append(getattr(row, "pos_noun"))
        features[i].append(getattr(row, "pos_pronoun"))
        features[i].append(getattr(row, "pos_verb"))
        features[i].append(getattr(row, "pos_other"))
        features[i].append(getattr(row, "pos_nums"))
        features[i].append(getattr(row, "complex_short"))
        features[i].append(getattr(row, "complex_medium"))
        features[i].append(getattr(row, "complex_long"))
        features[i].append(getattr(row, "vocab_level"))
        features[i].append(getattr(row, "pred_score"))
        features[i].append(getattr(row, "prompt_relevence"))
        features[i].append(getattr(row, "total_length"))
        #we get better results without the last two features
        #note that prompt_relevEnce is misspelled

        i += 1

    #cross validation classifying for this set
    print("10-fold cross-validation results for set ", set_array[set_num])
    clf = svm.SVC()
    cv_scores = cross_val_score(clf, features, scores, cv=10)
    print(cv_scores)
    print("Confusion matrix for set ", set_array[set_num])
    clf2 = svm.SVC()
    X_train, X_test, y_train, y_test = train_test_split(features, scores, test_size=0.33, random_state=42)
    y_pred = clf2.fit(X_train, y_train).predict(X_test)
    cnf_matrix = confusion_matrix(y_test, y_pred)
    print(cnf_matrix)
    
    set_num += 1

Splitting data for set  1
10-fold cross-validation results for set  1
[ 0.45238095  0.39880952  0.44642857  0.49404762  0.46706587  0.43113772
  0.46107784  0.41317365  0.49700599  0.41818182]
Confusion matrix for set  1
[[ 65  33  21   5]
 [ 35  45  47   8]
 [ 21  29 108  22]
 [  5  13  85  10]]
Splitting data for set  2
10-fold cross-validation results for set  2
[ 0.45736434  0.47286822  0.45736434  0.44186047  0.48062016  0.43410853
  0.4921875   0.46031746  0.48        0.464     ]
Confusion matrix for set  2
[[  3  31  14  11]
 [  1  43  40  13]
 [  1  22 108  37]
 [  0  12  63  23]]
Splitting data for set  3
10-fold cross-validation results for set  3
[ 0.65445026  0.61904762  0.61904762  0.62433862  0.62962963  0.63492063
  0.65608466  0.66137566  0.63492063  0.64893617]
Confusion matrix for set  3
[[  7 146   2]
 [  8 311   6]
 [  0  77  68]]
Splitting data for set  4
10-fold cross-validation results for set  4
[ 0.65445026  0.61904762  0.61904762  0.62433862  0.62962963  0.634