In [1]:
# required packages
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.model_selection import cross_val_score
import scipy as sp
import nltk
#from combined import combined
from sklearn.cross_validation import KFold
from sklearn.metrics import confusion_matrix
from combined import combined
from textstat.textstat import textstat
from sklearn.model_selection import train_test_split

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
# read short answer data
short = pd.read_csv("features_all.csv")

In [3]:
print(short)

      essay_id  score  org_score  pos_adjadv  pos_noun  pos_pronoun  pos_verb  \
0        24576      1          1           2         2            3         2   
1        24577      2          1           2         2            3         3   
2        24578      2          1           2         2            3         2   
3        24579      2          1           2         2            3         2   
4        24580      1          1           2         2            3         2   
5        24581      0          1           2         2            3         2   
6        24582      2          1           3         2            2         2   
7        24583      0          1           2         2            3         2   
8        24584      0          1           2         2            3         2   
9        24585      2          1           2         2            3         2   
10       24586      0          1           2         2            3         2   
11       24587      2       

In [7]:
#split into array of scores and array of other features
scores = []
features = []
i = 0
for row in short.itertuples(index=True, name='Pandas'):
    scores.append(getattr(row, "score"))
    features.append([])
    features[i].append(getattr(row, "org_score"))
    features[i].append(getattr(row, "pos_adjadv"))
    features[i].append(getattr(row, "pos_noun"))
    features[i].append(getattr(row, "pos_pronoun"))
    features[i].append(getattr(row, "pos_verb"))
    features[i].append(getattr(row, "pos_other"))
    features[i].append(getattr(row, "pos_nums"))
    features[i].append(getattr(row, "complex_short"))
    features[i].append(getattr(row, "complex_medium"))
    features[i].append(getattr(row, "complex_long"))
    features[i].append(getattr(row, "vocab_level"))
    #features[i].append(getattr(row, "predicted_score"))

    i += 1

In [8]:
#cross validation classifying for this set
clf = svm.SVC()
cv_scores = cross_val_score(clf, features, scores, cv=10)
print(cv_scores)

[ 0.67920354  0.57253599  0.7076412   0.71317829  0.71650055  0.54323725
  0.76607539  0.76607539  0.66740576  0.74028857]


In [9]:
clf2 = svm.SVC()
X_train, X_test, y_train, y_test = train_test_split(features, scores, test_size=0.33, random_state=42)
y_pred = clf2.fit(X_train, y_train).predict(X_test)
cnf_matrix = confusion_matrix(y_test, y_pred)
print(cnf_matrix)

[[509 464   1]
 [303 895   8]
 [  3  39 757]]


In [ ]:
#get features array by question set 
#set1 = pd.DataFrame() # essay ids 1 to 1672
#set2 = pd.DataFrame() #2788 to 4065
#set3 = pd.DataFrame() #4918 to 6808
#set4 = pd.DataFrame() #
#set5 = pd.DataFrame() #
#set6 = pd.DataFrame()
#set7 = pd.DataFrame()
#set8 = pd.DataFrame()
#set9 = pd.DataFrame()
#set10 = pd.DataFrame()


In [2]:
#AMER START HERE - THIS CODE IS FOR TRYING THE CLASSIFIER
#read data by set
set3 = pd.read_csv("new_data/short_set3.csv")
set4 = pd.read_csv("new_data/short_set4.csv")
set7 = pd.read_csv("new_data/short_set7.csv")
set8 = pd.read_csv("new_data/short_set8.csv")
set9 = pd.read_csv("new_data/short_set9.csv")

In [15]:

#print(set3)

      essay_id  set  score  org_score  pos_adjadv  pos_noun  pos_pronoun  \
0         4918    3      1          1           2         2            3   
1         4919    3      1          1           2         2            3   
2         4920    3      1          1           2         2            3   
3         4921    3      2          1           2         2            3   
4         4922    3      0          1           2         2            3   
5         4923    3      1          1           2         2            3   
6         4924    3      2          1           2         2            3   
7         4925    3      1          1           2         2            3   
8         4926    3      1          1           2         3            3   
9         4927    3      1          1           2         2            3   
10        4928    3      2          1           2         2            3   
11        4929    3      1          1           2         2            3   
12        49

In [4]:
# put all sets into a list for easy processing
all_data = [set3, set4, set7, set8, set9]

In [5]:
# for each set, get an array of features and an array of scores, and input these to classifier
set_num = 0
set_array = [3,4,7,8,9] #number of each set in the all_data list
for s in all_data:
    print("Splitting data for set ", set_array[set_num])
    #split into array of scores and array of other features
    scores = []
    features = []
    i = 0
    for row in s.itertuples(index=True, name='Pandas'):
        scores.append(getattr(row, "score"))
        features.append([])
        features[i].append(getattr(row, "org_score"))
        features[i].append(getattr(row, "pos_adjadv"))
        features[i].append(getattr(row, "pos_noun"))
        features[i].append(getattr(row, "pos_pronoun"))
        features[i].append(getattr(row, "pos_verb"))
        features[i].append(getattr(row, "pos_other"))
        features[i].append(getattr(row, "pos_nums"))
        features[i].append(getattr(row, "complex_short"))
        features[i].append(getattr(row, "complex_medium"))
        features[i].append(getattr(row, "complex_long"))
        features[i].append(getattr(row, "vocab_level"))
        #features[i].append(getattr(row, "pred_score"))

        i += 1

    #cross validation classifying for this set
    print("10-fold cross-validation results for set ", set_array[set_num])
    clf = svm.SVC()
    cv_scores = cross_val_score(clf, features, scores, cv=10)
    print(cv_scores)
    print("Confusion matrix for set ", set_array[set_num])
    clf2 = svm.SVC()
    X_train, X_test, y_train, y_test = train_test_split(features, scores, test_size=0.33, random_state=42)
    y_pred = clf2.fit(X_train, y_train).predict(X_test)
    cnf_matrix = confusion_matrix(y_test, y_pred)
    print(cnf_matrix)
    
    set_num += 1

Splitting data for set  3
10-fold cross-validation results for set  3
[ 0.52356021  0.52910053  0.51322751  0.52380952  0.52910053  0.52910053
  0.52910053  0.52380952  0.52910053  0.52659574]
Confusion matrix for set  3
[[  0 155   0]
 [  0 324   1]
 [  0 144   1]]
Splitting data for set  4
10-fold cross-validation results for set  4
[ 0.69714286  0.61142857  0.63218391  0.7183908   0.66091954  0.6091954
  0.65517241  0.71676301  0.68786127  0.63372093]
Confusion matrix for set  4
[[114  99   0]
 [ 44 274   1]
 [  0  36   6]]
Splitting data for set  7
10-fold cross-validation results for set  7
[ 0.56906077  0.52486188  0.52777778  0.54444444  0.53333333  0.5
  0.49444444  0.51111111  0.53631285  0.52808989]
Confusion matrix for set  7
[[308   4   8]
 [119   5   6]
 [126   5  13]]
Splitting data for set  8
10-fold cross-validation results for set  8
[ 0.57458564  0.54696133  0.54696133  0.6         0.52777778  0.51111111
  0.52222222  0.53631285  0.59217877  0.55617978]
Confusion matr

In [6]:
# THIS DOESN'T WORK!
# try again with linear kernel to get coef values
'''
set_num = 0
set_array = [3,4,7,8,9]
for s in all_data:
    print("Splitting data for set ", set_array[set_num])
    #split into array of scores and array of other features
    scores = []
    features = []
    i = 0
    for row in s.itertuples(index=True, name='Pandas'):
        scores.append(getattr(row, "score"))
        features.append([])
        features[i].append(getattr(row, "org_score"))
        features[i].append(getattr(row, "pos_adjadv"))
        features[i].append(getattr(row, "pos_noun"))
        features[i].append(getattr(row, "pos_pronoun"))
        features[i].append(getattr(row, "pos_verb"))
        features[i].append(getattr(row, "pos_other"))
        features[i].append(getattr(row, "pos_nums"))
        features[i].append(getattr(row, "complex_short"))
        features[i].append(getattr(row, "complex_medium"))
        features[i].append(getattr(row, "complex_long"))
        features[i].append(getattr(row, "vocab_level"))
        features[i].append(getattr(row, "pred_score"))

        i += 1

    #cross validation classifying for this set
    print("10-fold cross-validation results for set ", set_array[set_num])
    clf = svm.SVC(kernel='linear')
    cv_scores = cross_val_score(clf, features, scores, cv=10)
    print(cv_scores)
    #print(clf.coef_)
    print("Confusion matrix for set ", set_array[set_num])
    clf2 = svm.SVC(kernel='linear')
    X_train, X_test, y_train, y_test = train_test_split(features, scores, test_size=0.33, random_state=42)
    y_pred = clf2.fit(X_train, y_train).predict(X_test)
    cnf_matrix = confusion_matrix(y_test, y_pred)
    print(cnf_matrix)
    print(clf2.coef_)
    set_num += 1
    
    '''


Splitting data for set  3
10-fold cross-validation results for set  3
[ 0.7539267   0.75661376  0.74603175  0.75132275  0.74603175  0.75132275
  0.74074074  0.74603175  0.74603175  0.75      ]
Confusion matrix for set  3
[[  0 155   0]
 [  0 325   0]
 [  0  10 135]]
[[  5.68434189e-14  -5.32507881e-05  -5.74038212e-04  -2.27373675e-13
   -4.65853518e-04  -1.61014751e-04   3.65734733e-04   7.37538504e-04
   -3.87877256e-05  -6.98750779e-04  -2.62401045e-05   0.00000000e+00]
 [ -3.55271368e-15  -3.91300861e-06   8.14484164e-05  -1.42108547e-14
    5.63413622e-07  -7.10542736e-15   6.80501877e-05   7.41562483e-04
   -2.77401569e-04  -4.64160914e-04   2.07204117e-05  -2.00012842e+00]
 [  0.00000000e+00   1.33314892e-06   1.52599837e-04  -1.08127020e-03
    8.45980304e-05   9.51178279e-05   5.41317584e-05   1.75294573e-04
   -7.28374010e-05  -1.02457172e-04  -1.48188433e-05  -2.00032857e+00]]
Splitting data for set  4
10-fold cross-validation results for set  4
[ 0.72571429  0.61714286  0.6