In [1]:
import pandas as pd
import numpy as np
import nltk
import string
from nltk.corpus import stopwords
from nltk.util import ngrams
import string
from nltk import word_tokenize


In [2]:
from sklearn.neural_network import MLPClassifier

In [3]:
fil = pd.read_csv("C:\\Users\\Charu Saxena\\Documents\\project\\adm\\data\\features.csv")


In [4]:
fil1 = fil.copy()

In [6]:
fil_target= fil1["score"]
fil_target

0        1
1        1
2        1
3        0
4        2
5        1
6        1
7        3
8        3
9        2
10       0
11       3
12       2
13       2
14       0
15       0
16       3
17       0
18       0
19       3
20       0
21       2
22       0
23       3
24       1
25       2
26       2
27       0
28       3
29       2
        ..
17177    2
17178    2
17179    2
17180    0
17181    0
17182    1
17183    1
17184    2
17185    1
17186    2
17187    2
17188    2
17189    0
17190    1
17191    1
17192    2
17193    1
17194    2
17195    2
17196    0
17197    1
17198    1
17199    1
17200    1
17201    2
17202    1
17203    1
17204    1
17205    1
17206    0
Name: score, dtype: int64

In [8]:
fil_features = fil1
fil_features

essay_id  score  org_score  pos_adjadv  pos_noun  pos_pronoun  \
0             1      1          1    0.107143  0.178571          0.0   
1             2      1          1    0.083333  0.250000          0.0   
2             3      1          1    0.085714  0.228571          0.0   
3             4      0          1    0.058824  0.294118          0.0   
4             5      2          1    0.064516  0.193548          0.0   
5             6      1          1    0.041667  0.166667          0.0   
6             7      1          1    0.158537  0.219512          0.0   
7             8      3          1    0.076923  0.230769          0.0   
8             9      3          1    0.118644  0.186441          0.0   
9            10      2          1    0.084746  0.254237          0.0   
10           11      0          1    0.076923  0.307692          0.0   
11           12      3          1    0.097561  0.243902          0.0   
12           13      2          1    0.148936  0.212766          0.0   
13           14      2          1    0.000000  0.375000          0.0   
14           15      0          1    0.148148  0.185185          0.0   
15           16      0          1    0.125000  0.125000          0.0   
16           17      3          1    0.057692  0.346154          0.0   
17           18      0          1    0.119048  0.214286          0.0   
18           19      0          1    0.044444  0.333333          0.0   
19           20      3          1    0.084337  0.192771          0.0   
20           21      0          1    0.065217  0.130435          0.0   
21           22      2          1    0.068182  0.204545          0.0   
22           23      0          1    0.107143  0.142857          0.0   
23           24      3          1    0.113208  0.169811          0.0   
24           25      1          1    0.071429  0.285714          0.0   
25           26      2          1    0.086957  0.173913          0.0   
26           27      2          1    0.080000  0.200000          0.0   
27           28      0          1    0.071429  0.328571          0.0   
28           29      3          1    0.040000  0.240000          0.0   
29           30      2          1    0.136364  0.204545          0.0   
...         ...    ...        ...         ...       ...          ...   
17177     27559      2          1    0.195122  0.243902          0.0   
17178     27560      2          1    0.196078  0.333333          0.0   
17179     27561      2          1    0.190476  0.357143          0.0   
17180     27562      0          1    0.375000  0.250000          0.0   
17181     27563      0          1    0.333333  0.266667          0.0   
17182     27564      1          1    0.200000  0.300000          0.0   
17183     27565      1          1    0.153846  0.250000          0.0   
17184     27566      2          1    0.178571  0.295918          0.0   
17185     27567      1          1    0.236842  0.210526          0.0   
17186     27568      2          1    0.094340  0.320755          0.0   
17187     27569      2          1    0.174603  0.349206          0.0   
17188     27570      2          1    0.170213  0.340426          0.0   
17189     27571      0          1    0.571429  0.285714          0.0   
17190     27572      1          1    0.258065  0.193548          0.0   
17191     27573      1          1    0.142857  0.214286          0.0   
17192     27574      2          1    0.312500  0.125000          0.0   
17193     27575      1          1    0.173077  0.269231          0.0   
17194     27576      2          1    0.184211  0.271930          0.0   
17195     27577      2          1    0.215190  0.215190          0.0   
17196     27578      0          1    0.230769  0.307692          0.0   
17197     27579      1          1    0.363636  0.454545          0.0   
17198     27580      1          1    0.181818  0.363636          0.0   
17199     27581      1          1    0.380952  0.238095          0.0   
17200     27582      1          1    0.310345  

In [9]:
del fil_features['score']
del fil_features['essay_id']

In [10]:
fil_features

org_score  pos_adjadv  pos_noun  pos_pronoun  pos_verb  pos_other  \
0              1    0.107143  0.178571          0.0  0.178571   0.500000   
1              1    0.083333  0.250000          0.0  0.229167   0.375000   
2              1    0.085714  0.228571          0.0  0.171429   0.457143   
3              1    0.058824  0.294118          0.0  0.176471   0.470588   
4              1    0.064516  0.193548          0.0  0.290323   0.451613   
5              1    0.041667  0.166667          0.0  0.208333   0.583333   
6              1    0.158537  0.219512          0.0  0.170732   0.414634   
7              1    0.076923  0.230769          0.0  0.184615   0.507692   
8              1    0.118644  0.186441          0.0  0.254237   0.440678   
9              1    0.084746  0.254237          0.0  0.186441   0.457627   
10             1    0.076923  0.307692          0.0  0.153846   0.461538   
11             1    0.097561  0.243902          0.0  0.170732   0.487805   
12             1    0.148936  0.212766          0.0  0.234043   0.361702   
13             1    0.000000  0.375000          0.0  0.125000   0.500000   
14             1    0.148148  0.185185          0.0  0.203704   0.425926   
15             1    0.125000  0.125000          0.0  0.500000   0.250000   
16             1    0.057692  0.346154          0.0  0.153846   0.442308   
17             1    0.119048  0.214286          0.0  0.214286   0.440476   
18             1    0.044444  0.333333          0.0  0.155556   0.444444   
19             1    0.084337  0.192771          0.0  0.180723   0.506024   
20             1    0.065217  0.130435          0.0  0.239130   0.543478   
21             1    0.068182  0.204545          0.0  0.181818   0.500000   
22             1    0.107143  0.142857          0.0  0.285714   0.464286   
23             1    0.113208  0.169811          0.0  0.207547   0.509434   
24             1    0.071429  0.285714          0.0  0.214286   0.428571   
25             1    0.086957  0.173913          0.0  0.260870   0.463768   
26             1    0.080000  0.200000          0.0  0.200000   0.520000   
27             1    0.071429  0.328571          0.0  0.157143   0.271429   
28             1    0.040000  0.240000          0.0  0.200000   0.520000   
29             1    0.136364  0.204545          0.0  0.159091   0.454545   
...          ...         ...       ...          ...       ...        ...   
17177          1    0.195122  0.243902          0.0  0.170732   0.365854   
17178          1    0.196078  0.333333          0.0  0.117647   0.294118   
17179          1    0.190476  0.357143          0.0  0.119048   0.333333   
17180          1    0.375000  0.250000          0.0  0.062500   0.312500   
17181          1    0.333333  0.266667          0.0  0.200000   0.200000   
17182          1    0.200000  0.300000          0.0  0.100000   0.400000   
17183          1    0.153846  0.250000          0.0  0.153846   0.423077   
17184          1    0.178571  0.295918          0.0  0.122449   0.372449   
17185          1    0.236842  0.210526          0.0  0.210526   0.342105   
17186          1    0.094340  0.320755          0.0  0.094340   0.396226   
17187          1    0.174603  0.349206          0.0  0.095238   0.365079   
17188          1    0.170213  0.340426          0.0  0.170213   0.319149   
17189          1    0.571429  0.285714          0.0  0.000000   0.142857   
17190          1    0.258065  0.193548          0.0  0.096774   0.451613   
17191          1    0.142857  0.214286          0.0  0.214286   0.428571   
17192          1    0.312500  0.125000          0.0  0.125000   0.375000   
17193          1    0.173077  0.269231          0.0  0.115385   0.442308   
17194          1    0.184211  0.271930          0.0  0.122807   0.377193   
17195          1    0.215190  0.215190          0.0  0.164557   0.392405   
17196          1    0.230769  0.307692          0.0  0.153846   0.307692   
17197          1    0.363636  0.454545          0.0  0.

In [11]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)

In [12]:
clf.fit(fil_features, fil_target)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [13]:
from sklearn.model_selection import cross_val_score
rs = cross_val_score(clf, fil1, fil_target, cv=10)
rs

array([ 0.36041788,  0.44889663,  0.54270773,  0.59209762,  0.55026148,
        0.47674419,  0.44476744,  0.41046512,  0.35988372,  0.41303083])

In [14]:
print ("Accuracy %f" %cross_val_score(clf , fil1, fil['score'], cv=10, scoring='accuracy' ).mean())

Accuracy 0.459927


In [18]:
clf.n_layers_

4

In [19]:
from sklearn import linear_model
cl = linear_model.LogisticRegression()

In [20]:
cl.fit(fil_features, fil_target)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [23]:
rs1 = cross_val_score(cl, fil1, fil_target, cv=10)
rs1

array([ 0.34881021,  0.44657375,  0.55607205,  0.58221964,  0.56304474,
        0.47267442,  0.43662791,  0.38546512,  0.41627907,  0.51192554])

In [24]:
print ("Accuracy %f" %cross_val_score(cl , fil1, fil['score'], cv=10, scoring='accuracy' ).mean())

Accuracy 0.471969


In [27]:
cl.intercept_

array([ 1.0418126 , -0.60044072, -1.26672823, -2.123022  ])